export default {
  bug: require('../assets/pokemon/type/bug.png'),
  dark: require('../assets/pokemon/type/dark.png'),
  dragon: require('../assets/pokemon/type/dragon.png'),
  electric: require('../assets/pokemon/type/electric.png'),
  fairy: require('../assets/pokemon/type/fairy.png'),
  fighting: require('../assets/pokemon/type/fighting.png'),
  fire: require('../assets/pokemon/type/fire.png'),
  flying: require('../assets/pokemon/type/flying.png'),
  ghost: require('../assets/pokemon/type/ghost.png'),
  grass: require('../assets/pokemon/type/grass.png'),
  ground: require('../assets/pokemon/type/ground.png'),
  ice: require('../assets/pokemon/type/ice.png'),
  normal: require('../assets/pokemon/type/bug.png'),
  poison: require('../assets/pokemon/type/poison.png'),
  psychic: require('../assets/pokemon/type/bug.png'),
  rock: require('../assets/pokemon/type/rock.png'),
  steel: require('../assets/pokemon/type/steel.png'),
  water: require('../assets/pokemon/type/water.png'),
};
